import { Recipe } from './recipes-data'

export const THREE_INGREDIENT_RECIPES: Recipe[] = [
  {
    id: 'rec-3ing-01',
    title: 'Golden Garlic Butter Pasta',
    category: '15-Min Meals',
    prepTime: '2 mins',
    cookTime: '8 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Tender pasta tossed in sizzled minced garlic and rich melted butter. Pure comfort food.',
    ingredients: [
      { item: 'Short Pasta or Spaghetti', amount: '8 oz', category: 'Pantry & Grains', standardKey: 'pasta' },
      { item: 'Garlic', amount: '4 cloves minced', category: 'Produce', standardKey: 'garlic' },
      { item: 'Butter', amount: '3 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Boil pasta in salted water until al dente, reserving 1/4 cup pasta water.',
      'Melt butter in a skillet over medium-low heat; add minced garlic and cook for 1-2 minutes until fragrant and lightly golden.',
      'Toss drained pasta and reserved pasta water directly into the garlic butter skillet until glossy and coated.',
      'Season with black pepper to taste and serve immediately.'
    ],
    tags: ['pasta', 'garlic', 'butter', 'vegetarian', 'quick', 'easy'],
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=800&q=80',
    likes: 540,
  },
  {
    id: 'rec-3ing-02',
    title: 'Classic Fluffy Scrambled Eggs & Toast',
    category: 'Breakfast',
    prepTime: '2 mins',
    cookTime: '4 mins',
    servings: 1,
    difficulty: 'Easy',
    description: 'Silky, soft scrambled eggs cooked in melted butter and served over warm crisp toast.',
    ingredients: [
      { item: 'Eggs', amount: '3 large', category: 'Proteins', standardKey: 'eggs' },
      { item: 'Bread', amount: '2 slices', category: 'Pantry & Grains', standardKey: 'bread' },
      { item: 'Butter', amount: '1.5 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Toast your bread slices until golden brown.',
      'Whisk eggs vigorously with a pinch of salt until smooth and aerated.',
      'Melt butter in a nonstick skillet over medium-low heat, pour in eggs.',
      'Gently push curds across the pan with a spatula for 2-3 minutes until soft and custardy.',
      'Mound eggs onto the warm toast and enjoy immediately.'
    ],
    tags: ['breakfast', 'eggs', 'toast', 'butter', 'protein', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    likes: 620,
  },
  {
    id: 'rec-3ing-03',
    title: 'Crispy Cheddar Grilled Cheese',
    category: '15-Min Meals',
    prepTime: '2 mins',
    cookTime: '6 mins',
    servings: 1,
    difficulty: 'Easy',
    description: 'Golden, butter-crisped bread packed with thick melted cheddar cheese that pulls perfectly.',
    ingredients: [
      { item: 'Bread', amount: '2 slices', category: 'Pantry & Grains', standardKey: 'bread' },
      { item: 'Cheddar Cheese', amount: '2 thick slices', category: 'Dairy', standardKey: 'cheese' },
      { item: 'Butter', amount: '2 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Butter one side of each bread slice generously.',
      'Place one slice butter-side-down in a skillet over medium heat.',
      'Top with cheese, then cap with the second slice butter-side-up.',
      'Cook for 3 minutes per side until golden brown and the cheese is completely melted.'
    ],
    tags: ['lunch', 'cheese', 'bread', 'comfort food', 'vegetarian'],
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    likes: 890,
  },
  {
    id: 'rec-3ing-04',
    title: 'Savory Garlic Butter Chicken Bites',
    category: 'Dinner',
    prepTime: '3 mins',
    cookTime: '8 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Bite-sized chicken seared golden brown and basted in savory garlic butter sauce.',
    ingredients: [
      { item: 'Chicken Breast', amount: '1 lb diced', category: 'Proteins', standardKey: 'chicken' },
      { item: 'Garlic', amount: '5 cloves minced', category: 'Produce', standardKey: 'garlic' },
      { item: 'Butter', amount: '3 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Cut chicken breasts into bite-sized cubes and season with salt and pepper.',
      'Melt 1 tbsp butter in a large skillet over high heat; sear chicken pieces for 4-5 minutes until golden on all sides.',
      'Reduce heat to low, add remaining butter and minced garlic.',
      'Spoon bubbling garlic butter over the chicken for 2 minutes until cooked through and glossy.'
    ],
    tags: ['chicken', 'garlic', 'high protein', 'keto', 'dinner', 'easy'],
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80',
    likes: 710,
  },
  {
    id: 'rec-3ing-05',
    title: 'Simple Egg Fried Rice',
    category: '15-Min Meals',
    prepTime: '2 mins',
    cookTime: '6 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Fluffy scrambled eggs folded into fragrant jasmine rice with a touch of savory soy sauce.',
    ingredients: [
      { item: 'Cooked Rice', amount: '2 cups chilled', category: 'Pantry & Grains', standardKey: 'rice' },
      { item: 'Eggs', amount: '3 large beaten', category: 'Proteins', standardKey: 'eggs' },
      { item: 'Soy Sauce', amount: '2 tbsp', category: 'Spices & Sauces', standardKey: 'soy sauce' },
    ],
    instructions: [
      'Heat 1 tbsp cooking oil in a skillet or wok over medium-high heat.',
      'Pour in beaten eggs and soft scramble for 1 minute; break into bite-sized pieces.',
      'Add cold cooked rice, breaking up clumps with a wooden spatula.',
      'Drizzle soy sauce around the edges of the pan and toss vigorously for 3 minutes until steaming hot and golden.'
    ],
    tags: ['rice', 'eggs', 'asian', 'budget', 'quick', 'easy'],
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    likes: 950,
  },
  {
    id: 'rec-3ing-06',
    title: 'Cheesy Melted Omelette',
    category: 'Breakfast',
    prepTime: '2 mins',
    cookTime: '4 mins',
    servings: 1,
    difficulty: 'Easy',
    description: 'Golden French-style egg envelope filled with molten melted cheese and butter.',
    ingredients: [
      { item: 'Eggs', amount: '3 large', category: 'Proteins', standardKey: 'eggs' },
      { item: 'Cheese', amount: '1/2 cup shredded', category: 'Dairy', standardKey: 'cheese' },
      { item: 'Butter', amount: '1 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Beat eggs with a pinch of salt until completely smooth.',
      'Melt butter in a nonstick pan over medium heat; pour in eggs.',
      'As eggs set, sprinkle cheese across the center.',
      'Fold the sides over into a tri-fold omelette and slide onto a warm plate.'
    ],
    tags: ['breakfast', 'eggs', 'cheese', 'keto', 'high protein'],
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80',
    likes: 480,
  },
  {
    id: 'rec-3ing-07',
    title: 'Fresh Tomato & Garlic Olive Oil Pasta',
    category: 'Dinner',
    prepTime: '3 mins',
    cookTime: '9 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Juicy ripe tomatoes blistered in extra virgin olive oil with sliced garlic and tender pasta.',
    ingredients: [
      { item: 'Pasta', amount: '8 oz', category: 'Pantry & Grains', standardKey: 'pasta' },
      { item: 'Tomatoes', amount: '2 cups cherry or diced', category: 'Produce', standardKey: 'tomatoes' },
      { item: 'Garlic', amount: '4 cloves sliced', category: 'Produce', standardKey: 'garlic' },
    ],
    instructions: [
      'Boil pasta in salted water until al dente.',
      'Heat 3 tbsp olive oil in a skillet over medium heat; add garlic and cook 1 minute until fragrant.',
      'Add tomatoes and cook for 5 minutes, pressing lightly until they burst into a rich pan sauce.',
      'Toss drained pasta with the blistered tomato sauce.'
    ],
    tags: ['pasta', 'tomatoes', 'garlic', 'italian', 'vegan', 'mediterranean'],
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    likes: 560,
  },
  {
    id: 'rec-3ing-08',
    title: 'Skillet Potatoes & Sweet Onion Hash',
    category: '15-Min Meals',
    prepTime: '3 mins',
    cookTime: '12 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Cubed tender potatoes crisped in butter and tossed with sweet caramelized onions.',
    ingredients: [
      { item: 'Potatoes', amount: '3 medium diced', category: 'Produce', standardKey: 'potatoes' },
      { item: 'Onion', amount: '1 large sliced', category: 'Produce', standardKey: 'onion' },
      { item: 'Butter', amount: '2 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Dice potatoes into small 1/2 inch cubes for fast cooking.',
      'Melt butter with 1 tbsp oil in a heavy skillet over medium-high heat.',
      'Add potatoes and onions, cover with a lid for 5 minutes to steam.',
      'Uncover and sear for 6-7 minutes, flipping occasionally until golden brown and tender.'
    ],
    tags: ['potatoes', 'onion', 'budget', 'side dish', 'comfort food'],
    imageUrl: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?auto=format&fit=crop&w=800&q=80',
    likes: 420,
  },
  {
    id: 'rec-3ing-09',
    title: 'Crispy Cheesy Loaded Potatoes',
    category: 'Dinner',
    prepTime: '3 mins',
    cookTime: '10 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Pan-roasted tender potato bites smothered in melted cheddar cheese and butter.',
    ingredients: [
      { item: 'Potatoes', amount: '3 medium diced', category: 'Produce', standardKey: 'potatoes' },
      { item: 'Cheese', amount: '1 cup shredded cheddar', category: 'Dairy', standardKey: 'cheese' },
      { item: 'Butter', amount: '2 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Microwave diced potatoes for 3 minutes to par-cook.',
      'Melt butter in a skillet over medium heat; add potatoes and fry until crispy on all sides (about 5 mins).',
      'Turn off heat, cover potatoes with shredded cheese, and put a lid on the pan for 2 minutes until molten and bubbling.'
    ],
    tags: ['potatoes', 'cheese', 'comfort food', 'kids', 'dinner'],
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80',
    likes: 640,
  },
  {
    id: 'rec-3ing-10',
    title: 'Sizzling Beef & Onion Rice Bowl',
    category: 'Dinner',
    prepTime: '2 mins',
    cookTime: '8 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Juicy ground beef sautéed with caramelized onions served over steaming white rice.',
    ingredients: [
      { item: 'Ground Beef', amount: '1/2 lb', category: 'Proteins', standardKey: 'beef' },
      { item: 'Onion', amount: '1 medium sliced', category: 'Produce', standardKey: 'onion' },
      { item: 'Rice', amount: '2 cups cooked', category: 'Pantry & Grains', standardKey: 'rice' },
    ],
    instructions: [
      'Brown ground beef in a skillet over medium-high heat, breaking into crumbles.',
      'Add sliced onion and cook for 4-5 minutes until the onion is tender and lightly browned.',
      'Season with salt, pepper, and a dash of soy sauce if desired.',
      'Serve hot over bowls of fluffy white rice.'
    ],
    tags: ['beef', 'onion', 'rice', 'high protein', 'dinner', 'budget'],
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    likes: 780,
  },
  {
    id: 'rec-3ing-11',
    title: 'Warm Cheesy Beef Quesadilla',
    category: '15-Min Meals',
    prepTime: '2 mins',
    cookTime: '6 mins',
    servings: 1,
    difficulty: 'Easy',
    description: 'Crisp tortilla loaded with seasoned ground beef and melted gooey cheddar.',
    ingredients: [
      { item: 'Ground Beef', amount: '1/3 lb browned', category: 'Proteins', standardKey: 'beef' },
      { item: 'Cheese', amount: '3/4 cup shredded', category: 'Dairy', standardKey: 'cheese' },
      { item: 'Tortilla or Bread', amount: '2 tortillas', category: 'Pantry & Grains', standardKey: 'bread' },
    ],
    instructions: [
      'Brown ground beef in a skillet with salt and pepper; drain excess fat.',
      'Place one tortilla in a clean skillet over medium heat.',
      'Layer cheese, cooked ground beef, and more cheese; top with second tortilla.',
      'Cook for 3 minutes per side until crisp and golden brown.'
    ],
    tags: ['beef', 'cheese', 'quesadilla', 'mexican', 'high protein'],
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    likes: 820,
  },
  {
    id: 'rec-3ing-12',
    title: 'Sautéed Garlic Baby Spinach',
    category: '15-Min Meals',
    prepTime: '2 mins',
    cookTime: '3 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Tender vibrant spinach wilted in olive oil with slivers of golden aromatic garlic.',
    ingredients: [
      { item: 'Spinach', amount: '1 large bunch (8 oz)', category: 'Produce', standardKey: 'spinach' },
      { item: 'Garlic', amount: '4 cloves sliced', category: 'Produce', standardKey: 'garlic' },
      { item: 'Butter or Oil', amount: '2 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Heat butter or olive oil in a large skillet over medium heat.',
      'Add sliced garlic and sizzle for 1 minute until fragrant.',
      'Add washed spinach in batches, tossing gently with tongs until just wilted (about 2 minutes).',
      'Season with salt and a pinch of black pepper.'
    ],
    tags: ['spinach', 'garlic', 'healthy', 'keto', 'vegan', 'side dish'],
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&q=80',
    likes: 390,
  },
  {
    id: 'rec-3ing-13',
    title: 'Creamy Parmesan Butter Noodles',
    category: '15-Min Meals',
    prepTime: '2 mins',
    cookTime: '8 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Hot boiled pasta emulsified with sweet cream butter and freshly grated cheese.',
    ingredients: [
      { item: 'Pasta', amount: '8 oz', category: 'Pantry & Grains', standardKey: 'pasta' },
      { item: 'Butter', amount: '4 tbsp', category: 'Dairy', standardKey: 'butter' },
      { item: 'Cheese', amount: '3/4 cup grated', category: 'Dairy', standardKey: 'cheese' },
    ],
    instructions: [
      'Boil pasta in salted water until tender; reserve 1/3 cup pasta water.',
      'Drain pasta and return to the warm pot.',
      'Stir in butter, cheese, and a splash of reserved pasta water.',
      'Toss vigorously until a creamy, glossy cheese sauce coats every noodle.'
    ],
    tags: ['pasta', 'butter', 'cheese', 'kids', 'comfort food', 'italian'],
    imageUrl: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=800&q=80',
    likes: 670,
  },
  {
    id: 'rec-3ing-14',
    title: 'Golden Pan-Seared Lemon Chicken',
    category: 'Dinner',
    prepTime: '2 mins',
    cookTime: '10 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Juicy chicken breast seared crisp and brightened with fresh squeezed lemon juice and garlic.',
    ingredients: [
      { item: 'Chicken Breast', amount: '2 cutlets', category: 'Proteins', standardKey: 'chicken' },
      { item: 'Lemon', amount: '1 whole juiced', category: 'Produce', standardKey: 'lemon' },
      { item: 'Garlic', amount: '3 cloves minced', category: 'Produce', standardKey: 'garlic' },
    ],
    instructions: [
      'Pound chicken breasts to an even 1/2 inch thickness; season with salt and pepper.',
      'Heat 1 tbsp cooking oil in a skillet over medium-high heat.',
      'Sear chicken for 4 minutes per side until deeply browned.',
      'Reduce heat, add garlic and freshly squeezed lemon juice, swirling the pan for 1 minute to glaze the chicken.'
    ],
    tags: ['chicken', 'lemon', 'garlic', 'keto', 'high protein', 'dinner'],
    imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80',
    likes: 730,
  },
  {
    id: 'rec-3ing-15',
    title: 'Fresh Tomato & Melted Cheese Toast',
    category: 'Breakfast',
    prepTime: '2 mins',
    cookTime: '5 mins',
    servings: 1,
    difficulty: 'Easy',
    description: 'Toasted artisan bread topped with sweet sliced tomatoes and melted cheese.',
    ingredients: [
      { item: 'Bread', amount: '2 thick slices', category: 'Pantry & Grains', standardKey: 'bread' },
      { item: 'Tomatoes', amount: '1 large sliced', category: 'Produce', standardKey: 'tomatoes' },
      { item: 'Cheese', amount: '2 slices or 1/2 cup shredded', category: 'Dairy', standardKey: 'cheese' },
    ],
    instructions: [
      'Toast bread slices lightly in a toaster or skillet with butter.',
      'Arrange sliced fresh tomatoes on the bread, lightly salt them.',
      'Top with cheese and place under the oven broiler (or cover in skillet) for 3 minutes until bubbling and melted.'
    ],
    tags: ['breakfast', 'tomatoes', 'cheese', 'bread', 'vegetarian'],
    imageUrl: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?auto=format&fit=crop&w=800&q=80',
    likes: 490,
  },
  {
    id: 'rec-3ing-16',
    title: 'Sizzling Garlic Chicken & Rice Skillet',
    category: 'Dinner',
    prepTime: '3 mins',
    cookTime: '10 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Tender chicken bites and aromatic garlic stirred through warm rice for an effortless dinner.',
    ingredients: [
      { item: 'Chicken Breast', amount: '1 lb diced', category: 'Proteins', standardKey: 'chicken' },
      { item: 'Rice', amount: '2 cups cooked', category: 'Pantry & Grains', standardKey: 'rice' },
      { item: 'Garlic', amount: '4 cloves minced', category: 'Produce', standardKey: 'garlic' },
    ],
    instructions: [
      'Heat 1 tbsp oil in a skillet over high heat; sear chicken cubes for 5 minutes until cooked through.',
      'Add minced garlic and sauté for 1 minute until fragrant.',
      'Toss in cooked rice with 2 tbsp butter or soy sauce; stir-fry together for 3 minutes until steaming.'
    ],
    tags: ['chicken', 'rice', 'garlic', 'high protein', 'easy', 'dinner'],
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    likes: 850,
  },
  {
    id: 'rec-3ing-17',
    title: 'Fluffy Spinach & Cheese Scramble',
    category: 'Breakfast',
    prepTime: '2 mins',
    cookTime: '4 mins',
    servings: 1,
    difficulty: 'Easy',
    description: 'Whisked eggs scrambled with fresh baby spinach and pockets of molten melted cheese.',
    ingredients: [
      { item: 'Eggs', amount: '3 large', category: 'Proteins', standardKey: 'eggs' },
      { item: 'Spinach', amount: '1 cup fresh', category: 'Produce', standardKey: 'spinach' },
      { item: 'Cheese', amount: '1/3 cup shredded', category: 'Dairy', standardKey: 'cheese' },
    ],
    instructions: [
      'Wilt spinach in a lightly greased skillet for 1 minute over medium heat.',
      'Pour in whisked eggs with a pinch of salt and pepper.',
      'Gently scramble for 2 minutes until curds form; fold in cheese right before removing from heat.'
    ],
    tags: ['eggs', 'spinach', 'cheese', 'keto', 'breakfast', 'healthy'],
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80',
    likes: 510,
  },
  {
    id: 'rec-3ing-18',
    title: 'Pan-Fried Garlic Potato Bites',
    category: '15-Min Meals',
    prepTime: '3 mins',
    cookTime: '10 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Crispy cubed potatoes seasoned with fragrant golden garlic and rich melted butter.',
    ingredients: [
      { item: 'Potatoes', amount: '3 medium diced', category: 'Produce', standardKey: 'potatoes' },
      { item: 'Garlic', amount: '4 cloves minced', category: 'Produce', standardKey: 'garlic' },
      { item: 'Butter', amount: '2 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Dice potatoes small and microwave for 2 minutes to jump-start cooking.',
      'Melt butter and oil in a skillet over medium-high heat; fry potatoes for 6 minutes until crispy.',
      'Add minced garlic during the last 2 minutes, tossing until golden and aromatic.'
    ],
    tags: ['potatoes', 'garlic', 'butter', 'vegan-option', 'side dish'],
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80',
    likes: 600,
  },
  {
    id: 'rec-3ing-19',
    title: 'Savory Chinese Tomato & Egg Stir-Fry',
    category: '15-Min Meals',
    prepTime: '2 mins',
    cookTime: '6 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Classic home-style stir fry of juicy blistered tomatoes and tender fluffy scrambled eggs.',
    ingredients: [
      { item: 'Eggs', amount: '4 large beaten', category: 'Proteins', standardKey: 'eggs' },
      { item: 'Tomatoes', amount: '2 large diced', category: 'Produce', standardKey: 'tomatoes' },
      { item: 'Cooking Oil or Butter', amount: '2 tbsp', category: 'Dairy', standardKey: 'butter' },
    ],
    instructions: [
      'Scramble eggs in 1 tbsp oil over medium-high heat until just soft; transfer to a plate.',
      'Add remaining oil and diced tomatoes to the pan; cook 3-4 minutes until saucy and juices release.',
      'Add a pinch of salt and sugar, then return eggs to the pan and toss together for 1 minute.'
    ],
    tags: ['eggs', 'tomatoes', 'chinese', 'vegetarian', 'quick', 'easy'],
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    likes: 830,
  },
  {
    id: 'rec-3ing-20',
    title: 'Creamy Cheesy Rice Bake',
    category: 'Dinner',
    prepTime: '2 mins',
    cookTime: '6 mins',
    servings: 2,
    difficulty: 'Easy',
    description: 'Warm cooked rice folded with rich melted cheese and a splash of milk into comfort food bliss.',
    ingredients: [
      { item: 'Rice', amount: '2 cups cooked', category: 'Pantry & Grains', standardKey: 'rice' },
      { item: 'Cheese', amount: '1 cup shredded cheddar or jack', category: 'Dairy', standardKey: 'cheese' },
      { item: 'Milk or Butter', amount: '1/3 cup milk or 2 tbsp butter', category: 'Dairy', standardKey: 'milk' },
    ],
    instructions: [
      'Warm cooked rice in a saucepan or skillet with milk or butter over medium-low heat.',
      'Stir in shredded cheese a handful at a time until silky and completely melted.',
      'Season with salt and black pepper to taste.'
    ],
    tags: ['rice', 'cheese', 'kids', 'budget', 'comfort food'],
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    likes: 470,
  },
]
